### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xxjingyi** [He-lle/He-lle.github.io#1]
在css里添加以下代码：
`.next {
  text-align: right;
}`
在320行`<img src="button1.jpg">`改成`<img src="button1.jpg" class=".next">`
然后如果有能力可以把背景的图片变灰一点，增强可读性

**Comment by He-lle** [comment]
请详细说明，谢谢

**Comment by xxjingyi** [comment]
然后把上边320行的部分的i和m的空格还有<和>里面的空格删掉

**Comment by xxjingyi** [comment]
算了，把下面的复制，然后替换吧。
`<!DOCTYPE html>
<html>
<head>
<script>
  alert('这个网站的创建者是：一台名叫魏逸恺的电脑（B站账号，关注一下吧！）');
</script>
<link rel="SHORTCUT ICON" href="图标.ico">
<title>第一讲：Python概述</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
/* GitHub stylesheet for MarkdownPad (http://markdownpad.com) */
/* Author: Nicolas Hery - http://nicolashery.com */
/* Version: b13fe65ca28d2e568c6ed5d7f06581183df8f2ff */
/* Source: https://github.com/nicolahery/markdownpad-github */

/* RESET
=============================================================================*/

html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
}

/* BODY
=============================================================================*/

body {
  font-family: Helvetica, arial, freesans, clean, sans-serif;
  font-size: 14px;
  line-height: 1.6;
  color: #333;
  background-color: green;
  padding: 20px;
  max-width: 960px;
  margin: 0 auto;
}

body>*:first-child {
  margin-top: 0 !important;
}

body>*:last-child {
  margin-bottom: 0 !important;
}

/* BLOCKS
=============================================================================*/

p, blockquote, ul, ol, dl, table, pre {
  margin: 15px 0;
}

/* HEADERS
=============================================================================*/

h1, h2, h3, h4, h5, h6 {
  margin: 20px 0 10px;
  padding: 0;
  font-weight: bold;
  -webkit-font-smoothing: antialiased;
}

h1 tt, h1 code, h2 tt, h2 code, h3 tt, h3 code, h4 tt, h4 code, h5 tt, h5 code, h6 tt, h6 code {
  font-size: inherit;
}

h1 {
  font-size: 28px;
  color: #000;
}

h2 {
  font-size: 24px;
  border-bottom: 1px solid #ccc;
  color: #000;
}

h3 {
  font-size: 18px;
}

h4 {
  font-size: 16px;
}

h5 {
  font-size: 14px;
}

h6 {
  color: #777;
  font-size: 14px;
}

body>h2:first-child, body>h1:first-child, body>h1:first-child+h2, body>h3:first-child, body>h4:first-child, body>h5:first-child, body>h6:first-child {
  margin-top: 0;
  padding-top: 0;
}

a:first-child h1, a:first-child h2, a:first-child h3, a:first-child h4, a:first-child h5, a:first-child h6 {
  margin-top: 0;
  padding-top: 0;
}

h1+p, h2+p, h3+p, h4+p, h5+p, h6+p {
  margin-top: 10px;
}

/* LINKS
=============================================================================*/

a {
  color: #4183C4;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* LISTS
=============================================================================*/

ul, ol {
  padding-left: 30px;
}

ul li > :first-child, 
ol li > :first-child, 
ul li ul:first-of-type, 
ol li ol:first-of-type, 
ul li ol:first-of-type, 
ol li ul:first-of-type {
  margin-top: 0px;
}

ul ul, ul ol, ol ol, ol ul {
  margin-bottom: 0;
}

dl {
  padding: 0;
}

dl dt {
  font-size: 14px;
  font-weight: bold;
  font-style: italic;
  padding: 0;
  margin: 15px 0 5px;
}

dl dt:first-child {
  padding: 0;
}

dl dt>:first-child {
  margin-top: 0px;
}

dl dt>:last-child {
  margin-bottom: 0px;
}

dl dd {
  margin: 0 0 15px;
  padding: 0 15px;
}

dl dd>:first-child {
  margin-top: 0px;
}

dl dd>:last-child {
  margin-bottom: 0px;
}

/* CODE
=============================================================================*/

pre, code, tt {
  font-size: 12px;
  font-family: Consolas, "Liberation Mono", Courier, monospace;
}

code, tt {
  margin: 0 0px;
  padding: 0px 0px;
  white-space: nowrap;
  border: 1px solid #eaeaea;
  background-color: #f8f8f8;
  border-radius: 3px;
}

pre>code {
  margin: 0;
  padding: 0;
  white-space: pre;
  border: none;
  background: transparent;
}

pre {
  background-color: #f8f8f8;
  border: 1px solid #ccc;
  font-size: 13px;
  line-height: 19px;
  overflow: auto;
  padding: 6px 10px;
  border-radius: 3px;
}

pre code, pre tt {
  background-color: transparent;
  border: none;
}

kbd {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #DDDDDD;
    background-image: linear-gradient(#F1F1F1, #DDDDDD);
    background-repeat: repeat-x;
    border-color: #DDDDDD #CCCCCC #CCCCCC #DDDDDD;
    border-image: none;
    border-radius: 2px 2px 2px 2px;
    border-style: solid;
    border-width: 1px;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    line-height: 10px;
    padding: 1px 4px;
}

/* QUOTES
=============================================================================*/

blockquote {
  border-left: 4px solid #DDD;
  padding: 0 15px;
  color: #777;
}

blockquote>:first-child {
  margin-top: 0px;
}

blockquote>:last-child {
  margin-bottom: 0px;
}

/* HORIZONTAL RULES
=============================================================================*/

hr {
  clear: both;
  margin: 15px 0;
  height: 0px;
  overflow: hidden;
  border: none;
  background: transparent;
  border-bottom: 4px solid #ddd;
  padding: 0;
}

/* TABLES
=============================================================================*/

table th {
  font-weight: bold;
}

table th, table td {
  border: 1px solid #ccc;
  padding: 6px 13px;
}

table tr {
  border-top: 1px solid #ccc;
  background-color: #fff;
}

table tr:nth-child(2n) {
  background-color: #f8f8f8;
}

/* IMAGES
=============================================================================*/

img {
  max-width: 100%
}

.next {
  text-align: right;
}
</style>
</head>
<body style="background-size:100%;background-attachment: fixed;" background='大海.jpg'>
<p><center><font color=red size=72>第一讲:Python概述</p>
<h2></font></center></h2>
<p>Python是一种编程语言，它比很多其他的编程语言都简单，而且它是一种是完全面向对象的语言。<br>
Python的语法简单，初学者可以从Python入门，渐渐理解编程语言意义、作用，产生对编程的兴趣。<br>
Python有一种“库”的概念，“库”也分标准库和第三方库，这是以后才要讲的。<br>
Python标准库确实很庞大。它可以帮助处理各种工作，包括正则表达式、文档生成、单元测试、线程、数据库、网页浏览器、CGI、FTP、电子邮件、XML、XML-RPC、HTML、WAV文件、密码系统、GUI（图形用户界面）、Tk和其他与系统有关的操作。这被称作Python的“功能齐全”理念。除了标准库以外，还有许多其他高质量的库，如wxPython、Twisted和Python图像库等等。这里不需要记住，了解即可<br>
而且Python往往很美观，因为它有很强的模块化，而且强制缩进。什么是缩进？Python的缩进是为了区分代码块，等级关系而定的，所以是强制缩进，如果一些需要缩进的代码块没有缩进，那就无法运行。<br>
缩进该怎么在编程里体现出来呢？<br>
答案就是空格。一般来说是4个空格，当然缩进量（就是用几个空格）是可以在代码编辑器里调的，如果你不想打空格，就可以直接按Tab键表示一个缩进，更加方便。<br>
Python采用强制缩进的方式使得代码具有较好可读性，不想其他编程语言，比如C/C++、Java，用大括号分割代码块，导致代码杂乱，把初学者劝退。<br>
<font color=red>最重要的一点，Python属于解释性语言！</font><br>
什么是解释性语言？这里就不得不提到另一种语言：编译性语言。<br>
编译型语言的首先将源代码编译生成机器语言，再由机器运行机器码（二进制）。像C/C++等都是编译型语言。编译型语言：程序在执行之前需要一个专门的编译过程，把程序编译成 为机器语言的文件，运行时不需要重新翻译，所以执行速度较快。
解释型语言，是在运行的时候将程序翻译成机器语言。解释型语言的程序不需要在运行前编译，在运行程序的时候才翻译，专门的解释器负责在每个语句执行的时候解释程序代码。这样解释型语言每执行一次就要翻译一次，效率比较低。<br>
也就是高级语言需要解释执行或编译执行，那么Python就需要一个解释器。<br></p>
<h2>那么我们就需要在官网下载Python解释器，Python是官网是：<a href="http://www.python.org">官网</a><br></h2>
<p>由于是外网，可能访问有点慢，打开官网后，会看到右上角的大图标，那就是Python的图标。</p>
<img src="Python.jpg">
<p>由于配置Python解释器比较复杂，我会在一个文章里专门论述，就不在这里累述了，但是我必须说一句，如果你是初学者，那我建议你下载最新版本。<a href="https://blog.csdn.net/qq_45158642/article/details/127081622?ops_request_misc=&amp;request_id=&amp;biz_id=102&amp;utm_term=python%E8%A7%A3%E9%87%8A%E5%99%A8%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B&amp;utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-0-127081622.142^v68^control,201^v4^add_ask,213^v2^t3_esquery_v1&amp;spm=1018.2226.3001.4187">安装方法</a><br>
因链接中的文章是之前写的，里面的Python示例版本可能不是最新，你只要选择最新版本即可。<br>
<strong>本文涉及一些Python高级知识，对于看不懂的部分，可以跳过。</strong></p><br>
<p>如果有语法错误，请联系该电子邮箱，我们将第一时间修改：337986458@qq.com</p>
<a href="第二讲：Python的基本语法.html"><img src="button1.jpg" class="next"></a>

</body>
</html>
`
然后就是代码太乱，可读性太差，可以优化

**Comment by xxjingyi** [comment]
ok了，做了更改

**Comment by He-lle** [comment]
明白








                       
原始邮件
                       
                     

发件人："xxjingyi"< ***@***.*** &gt;;

发件时间：2023/4/13 19:30

收件人："He-lle/He-lle.github.io"< ***@***.*** &gt;;

抄送人："He-lle"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [He-lle/He-lle.github.io] 建议 (Issue #1)




 
ok了，做了更改
 
&mdash;

**Comment by He-lle** [comment]
知道了，这是程序生成的，不是我写的








                       
原始邮件
                       
                     

发件人："xxjingyi"< ***@***.*** &gt;;

发件时间：2023/4/13 19:28

收件人："He-lle/He-lle.github.io"< ***@***.*** &gt;;

抄送人："He-lle"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [He-lle/He-lle.github.io] 建议 (Issue #1)




 
算了，把下面的复制，然后替换吧。
 `
 <script&gt;   alert('这个网站的创建者是：一台名叫魏逸恺的电脑（B站账号，关注一下吧！）'); </script&gt; <title&gt;第一讲：Python概述</title&gt; <style type="text/css"&gt; /* GitHub stylesheet for MarkdownPad (http://markdownpad.com) */ /* Author: Nicolas Hery - http://nicolashery.com */ /* Version: b13fe65ca28d2e568c6ed5d7f06581183df8f2ff */ /* Source: https://github.com/nicolahery/markdownpad-github */ 
/* RESET
 =============================================================================*/
 
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
 margin: 0;
 padding: 0;
 border: 0;
 }
 
/* BODY
 =============================================================================*/
 
body {
 font-family: Helvetica, arial, freesans, clean, sans-serif;
 font-size: 14px;
 line-height: 1.6;
 color: #333;
 background-color: green;
 padding: 20px;
 max-width: 960px;
 margin: 0 auto;
 }
 
body&gt;*:first-child {
 margin-top: 0 !important;
 }
 
body&gt;*:last-child {
 margin-bottom: 0 !important;
 }
 
/* BLOCKS
 =============================================================================*/
 
p, blockquote, ul, ol, dl, table, pre {
 margin: 15px 0;
 }
 
/* HEADERS
 =============================================================================*/
 
h1, h2, h3, h4, h5, h6 {
 margin: 20px 0 10px;
 padding: 0;
 font-weight: bold;
 -webkit-font-smoothing: antialiased;
 }
 
h1 tt, h1 code, h2 tt, h2 code, h3 tt, h3 code, h4 tt, h4 code, h5 tt, h5 code, h6 tt, h6 code {
 font-size: inherit;
 }
 
h1 {
 font-size: 28px;
 color: #000;
 }
 
h2 {
 font-size: 24px;
 border-bottom: 1px solid #ccc;
 color: #000;
 }
 
h3 {
 font-size: 18px;
 }
 
h4 {
 font-size: 16px;
 }
 
h5 {
 font-size: 14px;
 }
 
h6 {
 color: #777;
 font-size: 14px;
 }
 
body&gt;h2:first-child, body&gt;h1:first-child, body&gt;h1:first-child+h2, body&gt;h3:first-child, body&gt;h4:first-child, body&gt;h5:first-child, body&gt;h6:first-child {
 margin-top: 0;
 padding-top: 0;
 }
 
a:first-child h1, a:first-child h2, a:first-child h3, a:first-child h4, a:first-child h5, a:first-child h6 {
 margin-top: 0;
 padding-top: 0;
 }
 
h1+p, h2+p, h3+p, h4+p, h5+p, h6+p {
 margin-top: 10px;
 }
 
/* LINKS
 =============================================================================*/
 
a {
 color: #4183C4;
 text-decoration: none;
 }
 
a:hover {
 text-decoration: underline;
 }
 
/* LISTS
 =============================================================================*/
 
ul, ol {
 padding-left: 30px;
 }
 
ul li &gt; :first-child,
 ol li &gt; :first-child,
 ul li ul:first-of-type,
 ol li ol:first-of-type,
 ul li ol:first-of-type,
 ol li ul:first-of-type {
 margin-top: 0px;
 }
 
ul ul, ul ol, ol ol, ol ul {
 margin-bottom: 0;
 }
 
dl {
 padding: 0;
 }
 
dl dt {
 font-size: 14px;
 font-weight: bold;
 font-style: italic;
 padding: 0;
 margin: 15px 0 5px;
 }
 
dl dt:first-child {
 padding: 0;
 }
 
dl dt&gt;:first-child {
 margin-top: 0px;
 }
 
dl dt&gt;:last-child {
 margin-bottom: 0px;
 }
 
dl dd {
 margin: 0 0 15px;
 padding: 0 15px;
 }
 
dl dd&gt;:first-child {
 margin-top: 0px;
 }
 
dl dd&gt;:last-child {
 margin-bottom: 0px;
 }
 
/* CODE
 =============================================================================*/
 
pre, code, tt {
 font-size: 12px;
 font-family: Consolas, "Liberation Mono", Courier, monospace;
 }
 
code, tt {
 margin: 0 0px;
 padding: 0px 0px;
 white-space: nowrap;
 border: 1px solid #eaeaea;
 background-color: #f8f8f8;
 border-radius: 3px;
 }
 
pre&gt;code {
 margin: 0;
 padding: 0;
 white-space: pre;
 border: none;
 background: transparent;
 }
 
pre {
 background-color: #f8f8f8;
 border: 1px solid #ccc;
 font-size: 13px;
 line-height: 19px;
 overflow: auto;
 padding: 6px 10px;
 border-radius: 3px;
 }
 
pre code, pre tt {
 background-color: transparent;
 border: none;
 }
 
kbd {
 -moz-border-bottom-colors: none;
 -moz-border-left-colors: none;
 -moz-border-right-colors: none;
 -moz-border-top-colors: none;
 background-color: #DDDDDD;
 background-image: linear-gradient(#F1F1F1, #DDDDDD);
 background-repeat: repeat-x;
 border-color: #DDDDDD #CCCCCC #CCCCCC #DDDDDD;
 border-image: none;
 border-radius: 2px 2px 2px 2px;
 border-style: solid;
 border-width: 1px;
 font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
 line-height: 10px;
 padding: 1px 4px;
 }
 
/* QUOTES
 =============================================================================*/
 
blockquote {
 border-left: 4px solid #DDD;
 padding: 0 15px;
 color: #777;
 }
 
blockquote&gt;:first-child {
 margin-top: 0px;
 }
 
blockquote&gt;:last-child {
 margin-bottom: 0px;
 }
 
/* HORIZONTAL RULES
 =============================================================================*/
 
hr {
 clear: both;
 margin: 15px 0;
 height: 0px;
 overflow: hidden;
 border: none;
 background: transparent;
 border-bottom: 4px solid #ddd;
 padding: 0;
 }
 
/* TABLES
 =============================================================================*/
 
table th {
 font-weight: bold;
 }
 
table th, table td {
 border: 1px solid #ccc;
 padding: 6px 13px;
 }
 
table tr {
 border-top: 1px solid #ccc;
 background-color: #fff;
 }
 
table tr:nth-child(2n) {
 background-color: #f8f8f8;
 }
 
/* IMAGES
 =============================================================================*/
 
img {
 max-width: 100%
 }
 
.next {
 text-align: right;
 }
 </style&gt;
 

第一讲:Python概述

 

 
Python是一种编程语言，它比很多其他的编程语言都简单，而且它是一种是完全面向对象的语言。
 Python的语法简单，初学者可以从Python入门，渐渐理解编程语言意义、作用，产生对编程的兴趣。
 Python有一种“库”的概念，“库”也分标准库和第三方库，这是以后才要讲的。
 Python标准库确实很庞大。它可以帮助处理各种工作，包括正则表达式、文档生成、单元测试、线程、数据库、网页浏览器、CGI、FTP、电子邮件、XML、XML-RPC、HTML、WAV文件、密码系统、GUI（图形用户界面）、Tk和其他与系统有关的操作。这被称作Python的“功能齐全”理念。除了标准库以外，还有许多其他高质量的库，如wxPython、Twisted和Python图像库等等。这里不需要记住，了解即可
 而且Python往往很美观，因为它有很强的模块化，而且强制缩进。什么是缩进？Python的缩进是为了区分代码块，等级关系而定的，所以是强制缩进，如果一些需要缩进的代码块没有缩进，那就无法运行。
 缩进该怎么在编程里体现出来呢？
 答案就是空格。一般来说是4个空格，当然缩进量（就是用几个空格）是可以在代码编辑器里调的，如果你不想打空格，就可以直接按Tab键表示一个缩进，更加方便。
 Python采用强制缩进的方式使得代码具有较好可读性，不想其他编程语言，比如C/C++、Java，用大括号分割代码块，导致代码杂乱，把初学者劝退。
 最重要的一点，Python属于解释性语言！
 什么是解释性语言？这里就不得不提到另一种语言：编译性语言。
 编译型语言的首先将源代码编译生成机器语言，再由机器运行机器码（二进制）。像C/C++等都是编译型语言。编译型语言：程序在执行之前需要一个专门的编译过程，把程序编译成 为机器语言的文件，运行时不需要重新翻译，所以执行速度较快。 解释型语言，是在运行的时候将程序翻译成机器语言。解释型语言的程序不需要在运行前编译，在运行程序的时候才翻译，专门的解释器负责在每个语句执行的时候解释程序代码。这样解释型语言每执行一次就要翻译一次，效率比较低。
 也就是高级语言需要解释执行或编译执行，那么Python就需要一个解释器。

 
那么我们就需要在官网下载Python解释器，Python是官网是：官网

 
由于是外网，可能访问有点慢，打开官网后，会看到右上角的大图标，那就是Python的图标。
 

 
由于配置Python解释器比较复杂，我会在一个文章里专门论述，就不在这里累述了，但是我必须说一句，如果你是初学者，那我建议你下载最新版本。安装方法
 因链接中的文章是之前写的，里面的Python示例版本可能不是最新，你只要选择最新版本即可。
 本文涉及一些Python高级知识，对于看不懂的部分，可以跳过。

 
***@***.***
  ` 然后就是代码太乱，可读性太差，可以优化 
&mdash;
